#!/bin/bash
#===============================================================================
# 02-locale.sh - Configurar locales
#===============================================================================

log_info "Configurando locales..."

# Generar locale
sudo locale-gen en_GB.UTF-8 > /dev/null 2>&1

# Configurar locale por defecto
sudo update-locale LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8

# Crear archivo de locale
sudo tee /etc/default/locale > /dev/null <<EOF
#  File generated by update-locale
LANG=en_GB.UTF-8
LC_ALL=en_GB.UTF-8
EOF

log_ok "Locales configurados (en_GB.UTF-8)"
